### PR TITLE
Add script to generate overrides CSS file

### PR DESCRIPTION
**Pull request by kadamwhite**
This naively transforms the built CSS to the subset of rules for ONLY
look-and-feel styles; anything not relating to font or color is removed.

I am working on getting Webpack to respect the ordering so that this sheet
loads last.

Sample generated CSS output:

```css
.topic-bar-chart .note {
  font-style: italic;
}

.topic-bar-chart .topic-bar-container {
  background-color: #bbb;
}

.topic-bar-chart .topic-bar {
  background-color: #838383;
}

.topic-bar-chart .bar-group.selected,
.topic-bar-chart .bar-group:focus,
.topic-bar-chart .bar-group:hover {
  outline-color: hsla(0,0%,60%,.1);
}

.topic-bar-chart .bar-group.selected .topic-bar,
.topic-bar-chart .bar-group:focus .topic-bar,
.topic-bar-chart .bar-group:hover .topic-bar {
  background-color: red;
}
```
We could make this smarter, or use it as a basis for a curated subset, or leave it as-is; thoughts?

### CODE REVIEW

**Comment by kadamwhite** [comment]
Note that when run from within the build script, this outputs the overrides file into both the `public/` _and_ the `build/` directories, through the magic of that existing build script. We'll probably want to commit the local version in `public/` so that we don't encounter a 404 on a missing stylesheet when checking out a new repo.

**Comment by kadamwhite** [comment]
Hold on merging, addressing issues with assistance from @mzgoddard

**Comment by iros** [comment]
@kadamwhite testing locally

**Comment by kadamwhite** [comment]
@iros test the generation and give me your thoughts on the output content, but this doesn't quite get injected right currently

**Review by pbeshai — APPROVED** [review]

**Comment by kadamwhite** [comment]
This now runs only on the _production_ Webpack build, and injects the built file into the `build/` directory as `build/overrides.css`.

**Pull request merged**
